application: yetanotheriching
version: 1
runtime: python
api_version: 1



# if you're adding the shell to your own app, change this regex url to the URL
# endpoint where you want the shell to run, e.g. /shell . You'll also probably
# want to add login: admin to restrict to admins only.
inbound_services:
- mail

handlers:
  
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin


- url: /_ah/mail/.+ 
  script: handle_incoming_email.py 
  login: admin

- url: /static
  static_dir: static
  
- url: /templates
  static_dir: static

- url: /(.*\.(jpg))
  static_files: images/\1
  upload: images/(.*\.(jpg))
  
- url: /(.*\.(png))
  static_files: images/\1
  upload: images/(.*\.(png))
  
- url: /(.*\.(gif))
  static_files: images/\1
  upload: images/(.*\.(gif))

- url: /(.*\.(pdf))
  static_files: static/\1
  upload: static/(.*\.(pdf))


- url: /css
  static_dir: css

- url: /favicon.ico
  static_files: static/path-tracker-small.png
  upload: static/path-tracker-small.png
  
- url: /admin/path_entry
  script: admin.py
  login: admin
  


- url: .*
  script: yetanotheriching.py